example: true

#Refrences to CarePackage Class Files
#How it works... 
#<name>:
#    package: com.example.Example
#    name: ยง5Example Care Package
# package - Package of class and 
#
#
#
carepackages: 
  